version: '2'
services:
  rethinkdb:
    image: rethinkdb
    ports:
     - "28015:28015"
     - "7777:8080"
    volumes:
     - ./data:/data
    command: rethinkdb --bind all
  websockets:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "9898:9898"
