version: '2'
services:
  websocket:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "9898:9898"
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
  rethinkdb:
    image: rethinkdb
    ports:
     - "28015:28015"
    volumes:
     - ./data:/data
    #command: rethinkdb --bind all

